# Generated by Django 3.1.3 on 2020-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('verdict', models.CharField(blank=True, max_length=10, null=True)),
                ('error_message', models.CharField(blank=True, max_length=100, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=10, null=True)),
                ('mem_used', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
