# Generated by Django 3.1.3 on 2020-12-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='error_message',
            new_name='message',
        ),
    ]
